# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sravan Patchala
tagline:          ''
description:      'An electrical Engineering Undergraduate at IIT Bombay'
url:              https://sravps7.github.io/
baseurl:          /

author:
  name:           'Sravan Patchala'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sravps7/sravps7.github.io
